# Generated by Django 5.2.14 on 2026-05-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0006_post_authoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authoe',
            new_name='author',
        ),
    ]
